id: A9294D92A
title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
type: translation
pechas:
- I215D48CA
- I073777D3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:50.196861
  last_modified_at: 2023-01-04 12:43:50.196880
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I215D48CA/B934: '1994'
  I073777D3/1CE6: '1994'
